aggregation:
  # Name for the aggregated report
  name: "Test CI Team"
  projects:
    - "test-ci-team1"
    - "test-ci-team2"

# Required for multiple scenario
output_dir: "reports/test-ci-aggregated"
# Remove old reports when we rerun ci jobs
replace_existing_reports: true
